/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.*

class AppTest {
    @Test
    fun appHasAGreeting() {
        val classUnderTest = App()
        
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }

    @Test
    fun checkHelloMethod() {
        val classUnderTest = App()

        assertEquals("Buy", classUnderTest.sayHello())
    }
}
